services:
    phpro_soap_client_bridge_demo.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        tags:
            - { name: phpro_soap_client.event_dispatcher }

    phpro_soap_client_bridge_demo.weather:
        class: Phpro\SoapClient\BridgeDemoBundle\WeatherClient\WeatherClient
        factory: [Phpro\SoapClient\BridgeDemoBundle\WeatherClient\WeatherClientFactory, factory]
        arguments:
            - @event_dispatcher