services:
    phpro_soap_client_bridge_demo.weather:
        class: Phpro\SoapClient\BridgeDemoBundle\WeatherClient\WeatherClient
        factory: [Phpro\SoapClient\BridgeDemoBundle\WeatherClient\WeatherClientFactory, factory, [@phpro_soap_client_bridge.collector]]
